version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  python: circleci/python@2.0

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          requirements-file: requirements.txt
      - run:
          name: Run tests
          command: |
            pytest tests/ --cov=./ --cov-report=xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report

  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_USERNAME/churn-prediction-api
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_USERNAME/churn-prediction-api
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main