version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t churn-prediction-app:latest .

  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Deploy to staging/production
          command: |
            echo "Deploying to staging/production..."
            # Add your deployment script here (e.g., Kubernetes, AWS ECS, etc.)

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main  # Only deploy from the main branch